export const GET_SECTIONS_LIST = 'GET_SECTIONS_LIST';
export const GET_CHAPTERS_LIST = 'GET_CHAPTERS_LIST';
export const GET_KURALS_LIST = 'GET_KURALS_LIST';
export const GET_ONE_KURAL = 'GET_ONE_KURAL';
export const GET_ALL_CHAPTERS = 'GET_ALL_CHAPTERS';